### ISSUE TITLE
Changer ordre des boutons sur un article

### ISSUE THREAD

**Issue by emporeso2** [tontof/kriss_feed#391]
Sur chaque article peut on changer facilement l'ordre des boutons share/read/star ?

**Comment by tontof** [comment]
A priori oui avec un user.css et quelque chose qui ressemble à ça:
```css
.item-title { display:flex;}
.item-mark-as{ order: -1;}
```
pour mettre en premier le bouton ```read```
