### ISSUE TITLE
Preview list mode available?

### ISSUE THREAD

**Issue by poVoq** [tontof/kriss_feed#396]
First off, very cool application, will probably replace (the also cool) Selfoss on my system.

Is it possible to have a preview list mode that shows the first few sentences of an entry and adds a "read more" to the source? The feeds I have are typically are long articles thus the expanded view is not very practical. However the list view seems a bit too condensed.

**Comment by tontof** [comment]
I guess you have 2 solutions for that using a custom css: https://tontof.net/kriss/feed/#css-user
- in expanded view, you can add a fixed height with a scroll
```css
.item-content {
    max-height: 250px;
    overflow: auto;
}
```
- in list view (with + as read more), you can display the condensed preview differently with that for example:
```css
.item-description {display: block;}
.item-info {white-space: normal;}
.muted{color:#000;}
```
