### ISSUE TITLE
Vidéos Youtube non responsive

### ISSUE THREAD

**Issue by Ironfly007** [tontof/kriss_feed#407]
Bonjour Tontof,

Je n'arrive pas à rendre les vidéos Youtube responsive.
Sur mobile, les vidéos sont tronquées ce qui les rend illisibles.

J'ai essayé de modifier mon CSS mais c'est pas top. Les vidéos ont des barres noires de chaque côté ou en haut et en bas.

Je m'étais inspiré de ceci : https://qualifio.zendesk.com/hc/fr/articles/115012572747-Comment-rendre-un-embed-iframe-video-parfaitement-responsive

Aurais tu une idée pour modifier ça correctement ?

**Comment by tontof** [comment]
Salut,
Je suis désolé, je n'ai pas le souvenir d'avoir reçu ton message d'où ma non-réponse... Je viens de tomber par hasard sur ta question.
Je ne sais pas si tu as trouvé des solutions mais tu dois pouvoir utiliser quelque chose qui ressemble à ça (en ajoutant des media query en fonction de la largeur de l'écran et si tu affiches la liste des flux) :
```css
.item-content > article > iframe[src^="https://www.youtube.com"] {
    width: 100vw;
    height: calc(100vw * (360 / 640));
    max-width: 640px;
    max-height: 360px;
}
```
