### ISSUE TITLE
Coloration syntaxique

### ISSUE THREAD

**Issue by Nono-m0le** [tontof/kriss_feed#408]
tontooooooooff

J'ai un petit souci de rendu sur 1 article (ca vient d'un blog static sous Hugo).
L'article en quesiton : https://lord.re/fast-posts/23-tsmpcd/
Le type de rendu sur kriss feed : https://i.imgur.com/3B4bjCO.png

Tu penses que tu peux faire quelques chose, ou ca viendrait du theme Hugo utilisé ?

**Comment by tontof** [comment]
Je ne sais plus si tu as un user.css mais il suffit d'ajouter
```css
code {
  background-color: initial;
  border: none;
}
```
Voici le rendu
https://tontof.net/feed/?currentHash=kErViA
